### ISSUE TITLE
Add <format type="text/markdown"> as an insertable element

### ISSUE THREAD

**Issue by dend** [xamarin/DocWriter#7]
This is related to [this mdoc issue](https://github.com/mono/api-doc-tools/issues/14) - we are leveraging a lot of Markdown content in our publishing system, and it would be great if we can use DocWriter to edit it within ECMA XML files.

**Comment by jonpryor** [comment]
I'm coming at this from the mdoc tooling perspective...and I don't know what's being asked for here. :-(

Do you have an example use case? An example workflow? What document is being edited, what is the user entering, etc.?

**Comment by joelmartinez** [comment]
If I could offer a proposal ... what if `<format type="text/markdown">` is simply a specially marked `div` in the WYSIWYG editor. The user can edit the text accordingly, and when it's time to convert into ecmaXml, [the converter](https://github.com/xamarin/DocWriter/blob/master/Convert/DocConverter.cs) can simply translate the contained content into markdown and a `format` tag, when saving to the xml.

We would probably just end up taking a dependency on [CommonMark.net](https://github.com/Knagis/CommonMark.NET), since they have a nice [AST](https://github.com/Knagis/CommonMark.NET/tree/master/CommonMark/Syntax) model for markdown content (so we can render markdown *from* html in the [the converter](https://github.com/xamarin/DocWriter/blob/master/Convert/DocConverter.cs))

**Comment by dend** [comment]
@jonpryor for one of the recent releases, we introduced the ability to add Markdown embeds through `<format type="text/markdown">` in **Remarks**. As we look into DocWriter as the primary editing tool for ECMAXML, we need a way to edit Markdown within DocWriter itself for docs that have it. 

I like the proposal that @joelmartinez has put forth - I think it solves our ask.

**Comment by migueldeicaza** [comment]
We could also upgrade to ProseMirror, but someone needs to figure out the schema for this, as ProseMirror can edit to a schema directly.
